# Generated by Django 3.0.3 on 2020-07-10 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initialPrice',
            field=models.PositiveIntegerField(),
        ),
    ]
