# Generated by Django 3.0.3 on 2020-07-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200710_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myListings',
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(),
        ),
    ]
